import { readFileSync } from 'fs'
let handler = async (m, {conn, command, args, usedPrefix}) => {
let ktnya = ['\n\n\n' + htjava + ' Mungkin menu ini bermanfaat? ' + htjava,
 '\n\n\n' + htjava + ' Terimakasih sudah menggunakan bot ini ' + htjava,
 '\n\n\n' + htjava + ' Semoga gak erorr ' + htjava,
 '\n\n\n' + htjava + ' Jika lama kemungkiman erorr atau delay ' + htjava,
 '\n\n\n' + htjava + ' Menampilkan menu ' + htjava,
 '\n\n\n' + htjava + ' Wait... ' + htjava,
 '\n\n\n' + htjava + ' Dua tiga kucing berlari ' + htjava,
 '\n\n\n' + htjava + ' Bentar bang akan kutampilkan menunya ' + htjava,
 '\n\n\n' + htjava + ' Prosess... ' + htjava]
let ktx = ktnya.getRandom()
const sections = [
   {
	title: `${htki} RPG GAME ${htka}`,
	rows: [
	    {title: `${emojis} adventure`.toUpperCase(), rowId: `${usedPrefix}adventure`, description: ktx},
	    {title: `${emojis} bansos`.toUpperCase(), rowId: `${usedPrefix}bansos`, description: ktx},
	    {title: `${emojis} buy`.toUpperCase(), rowId: `${usedPrefix}buy`, description: ktx},
	    {title: `${emojis} berburu`.toUpperCase(), rowId: `${usedPrefix}berburu`, description: ktx},
	    {title: `${emojis} berdagang`.toUpperCase(), rowId: `${usedPrefix}berdagang`, description: ktx},
	    {title: `${emojis} berkebon`.toUpperCase(), rowId: `${usedPrefix}berkebon`, description: ktx},
	    {title: `${emojis} bet`.toUpperCase(), rowId: `${usedPrefix}bet`, description: ktx},
	    {title: `${emojis} build`.toUpperCase(), rowId: `${usedPrefix}build`, description: ktx},
	    {title: `${emojis} casino`.toUpperCase(), rowId: `${usedPrefix}casino`, description: ktx},
	    {title: `${emojis} cek`.toUpperCase(), rowId: `${usedPrefix}cek`, description: ktx},
	    {title: `${emojis} chop`.toUpperCase(), rowId: `${usedPrefix}chop`, description: ktx},
	    {title: `${emojis} collect`.toUpperCase(), rowId: `${usedPrefix}collect`, description: ktx},
	    {title: `${emojis} cook`.toUpperCase(), rowId: `${usedPrefix}cook`, description: ktx},
	    {title: `${emojis} cooldown`.toUpperCase(), rowId: `${usedPrefix}cooldown`, description: ktx},
	    {title: `${emojis} craft`.toUpperCase(), rowId: `${usedPrefix}craft`, description: ktx},
	    {title: `${emojis} daily`.toUpperCase(), rowId: `${usedPrefix}daily`, description: ktx},
	    {title: `${emojis} duel`.toUpperCase(), rowId: `${usedPrefix}duel`, description: ktx},
	    {title: `${emojis} dungeon`.toUpperCase(), rowId: `${usedPrefix}dungeon`, description: ktx},
	    {title: `${emojis} eat`.toUpperCase(), rowId: `${usedPrefix}eat`, description: ktx},
	    {title: `${emojis} feed`.toUpperCase(), rowId: `${usedPrefix}feed`, description: ktx},
	    {title: `${emojis} heal`.toUpperCase(), rowId: `${usedPrefix}heal`, description: ktx},
	    {title: `${emojis} hourly`.toUpperCase(), rowId: `${usedPrefix}hourly`, description: ktx},
	    {title: `${emojis} hunt`.toUpperCase(), rowId: `${usedPrefix}hunt`, description: ktx},
	    {title: `${emojis} inventory`.toUpperCase(), rowId: `${usedPrefix}inventory`, description: ktx},
	    {title: `${emojis} kandang`.toUpperCase(), rowId: `${usedPrefix}kandang`, description: ktx},
	    {title: `${emojis} kerja`.toUpperCase(), rowId: `${usedPrefix}kerja`, description: ktx},
	    {title: `${emojis} koboy`.toUpperCase(), rowId: `${usedPrefix}koboy`, description: ktx},
	    {title: `${emojis} kolam`.toUpperCase(), rowId: `${usedPrefix}kolam`, description: ktx},
	    {title: `${emojis} leaderboard`.toUpperCase(), rowId: `${usedPrefix}leaderboard`, description: ktx},
	    {title: `${emojis} mancing`.toUpperCase(), rowId: `${usedPrefix}mancing`, description: ktx},
	    {title: `${emojis} mentransfer`.toUpperCase(), rowId: `${usedPrefix}mentransfer`, description: ktx},
	    {title: `${emojis} merampok`.toUpperCase(), rowId: `${usedPrefix}merampok`, description: ktx},
	    {title: `${emojis} mining`.toUpperCase(), rowId: `${usedPrefix}mining`, description: ktx},
	    {title: `${emojis} mission`.toUpperCase(), rowId: `${usedPrefix}mission`, description: ktx},
	    {title: `${emojis} monthly`.toUpperCase(), rowId: `${usedPrefix}monthly`, description: ktx},
	    {title: `${emojis} nabung`.toUpperCase(), rowId: `${usedPrefix}nabung`, description: ktx},
	    {title: `${emojis} nambang`.toUpperCase(), rowId: `${usedPrefix}nambang`, description: ktx},
	    {title: `${emojis} nebang`.toUpperCase(), rowId: `${usedPrefix}nebang`, description: ktx},
	    {title: `${emojis} ngocok`.toUpperCase(), rowId: `${usedPrefix}ngocok`, description: ktx},
	    {title: `${emojis} nguli`.toUpperCase(), rowId: `${usedPrefix}nguli`, description: ktx},
	    {title: `${emojis} ojek`.toUpperCase(), rowId: `${usedPrefix}ojek`, description: ktx},
	    {title: `$